apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  labels:
    app.kubernetes.io/name: smartlinks
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: smartlinks
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik