// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartLinks.Management.Infrastructure.Persistence;

#nullable disable

namespace SmartLinks.Management.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ManagementDbContext))]
    partial class ManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartLinks.Management.Domain.SmartLinks.SmartLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DefaultUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_smart_links_slug");

                    b.ToTable("smart_links", "management");
                });

            modelBuilder.Entity("SmartLinks.Management.Infrastructure.Persistence.Publication.Entities.ConfigurationChangeEntity", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Revision"));

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<Guid>("SmartLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("smart_link_id");

                    b.HasKey("Revision");

                    b.HasIndex("SmartLinkId")
                        .HasDatabaseName("ix_configuration_changes_smart_link_id");

                    b.ToTable("configuration_changes", "management");
                });

            modelBuilder.Entity("SmartLinks.Management.Infrastructure.Persistence.Publication.Entities.PublishedSmartLinkEntity", b =>
                {
                    b.Property<Guid>("SmartLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("smart_link_id");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.HasKey("SmartLinkId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_published_smart_links_slug");

                    b.ToTable("published_smart_links", "management");
                });

            modelBuilder.Entity("SmartLinks.Management.Domain.SmartLinks.SmartLink", b =>
                {
                    b.OwnsMany("SmartLinks.Management.Domain.SmartLinks.SmartLinkRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("smart_link_id")
                                .HasColumnType("uuid")
                                .HasColumnName("smart_link_id");

                            b1.Property<int>("Priority")
                                .HasColumnType("integer")
                                .HasColumnName("priority");

                            b1.Property<string>("ConditionDsl")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("condition_dsl");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("is_enabled");

                            b1.Property<string>("TargetUrl")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("target_url");

                            b1.HasKey("smart_link_id", "Priority");

                            b1.ToTable("smart_link_rules", "management");

                            b1.WithOwner()
                                .HasForeignKey("smart_link_id");
                        });

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
